[package]
name = "vm"
version = "0.2.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
culpa = "1.0.2"
liso = "1.2.1"
maplit = "1.0.2"
miette = { version = "7.2.0", features = ["fancy"] }
tabular = "0.2.0"
thiserror = "1.0.61"
